# Generated by Django 3.1.3 on 2021-02-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetail',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
