# Generated by Django 3.1.3 on 2021-02-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_auto_20210227_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imagedetail',
            name='price',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
