# Generated by Django 3.1.3 on 2021-02-28 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0006_auto_20210227_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetail',
            name='type',
        ),
    ]
