# Generated by Django 3.1.3 on 2021-03-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0008_auto_20210319_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_image', to='AdminPanel.imagedetail'),
        ),
    ]
