# Generated by Django 3.1.3 on 2021-03-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0009_auto_20210323_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
