# Generated by Django 3.1.7 on 2021-02-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_image',
            field=models.ImageField(blank=True, default='profileDefault.jpg', null=True, upload_to=''),
        ),
    ]
