# Generated by Django 3.1.3 on 2021-03-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0007_auto_20210311_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
