# Generated by Django 3.1.3 on 2021-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0009_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
