# Generated by Django 3.1.3 on 2021-03-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0012_wallet_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_id',
        ),
    ]
