# Generated by Django 3.1.3 on 2021-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0017_remove_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
