# Generated by Django 3.1.3 on 2021-03-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0018_auto_20210323_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_name',
        ),
    ]
